"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Preeratee Rojpanich and Sadie Zielinski, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: pr25257
UT EID 2: snz298
"""

def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start + 1 > len(nums):
        return target == 0
    if group_sum(start + 1, nums, target - nums[start]):
        return True
    return group_sum(start + 1, nums, target)


def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start + 1 > len(nums):
        return target == 0
    if nums[start] == 6:
        if group_sum_6(start + 1, nums, target - nums[start]):
            return True
        else:
            return False
    if group_sum_6(start + 1, nums, target - nums[start]):
        return True
    return group_sum_6(start + 1, nums, target)



def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start + 1 > len(nums):
        return target == 0
    if group_no_adj(start + 2, nums, target - nums[start]):
        return True
    return group_no_adj(start + 1, nums, target)




def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start + 1 > len(nums):
        return target == 0
    if nums[start] % 5 == 0:
        if group_sum_5(start + 1, nums, target - nums[start]):
            return True
        else:
            return False
    if group_sum_5(start + 1, nums, target - nums[start]):
        return True
    return group_sum_5(start + 1, nums, target)


def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    pass





def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    #add for commit
    nums_sum = sum(nums)

    if len(nums) == 0:
        return True
    if len(nums) == 1:
        return False
    if nums_sum % 2 != 0:
        return False

    def recursive_helper(index, help_sum, nums_sum_update):
        #print(index, help_sum, nums_sum_update)
        if help_sum > nums_sum / 2:
            return False
        if help_sum == nums_sum / 2:
            return True
        if index >= len(nums):
            return False

        help_sum = help_sum + nums[index]
        if recursive_helper(index + 1, help_sum , nums_sum_update ):
            return True
        help_sum = help_sum - nums[index]

        return recursive_helper(index + 1, help_sum, nums_sum_update - nums[index])

    return recursive_helper(0, 0, nums_sum)



def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if len(nums) == 0:
        return False

    if len(nums) == 1:
        if nums[0] % 2 == 1:
            return True
        else:
            return False

    def recursive_helper(index, ten, odd):
        if index == len(nums):
            if odd % 2 == 1 and ten % 10 == 0:
                return True
            else:
                return False
        ten = ten + nums[index]
        if recursive_helper(index+1, ten , odd):
            return True
        ten = ten - nums[index]
        odd = odd + nums[index]
        if recursive_helper(index+1, ten , odd):
            return True
        return False
    return recursive_helper(0, 0 , 0)




def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    nums_sum = sum(nums)
    if len(nums) == 0:
        return False
    if len(nums) == 1:
        return False
    if nums_sum % 2 != 0:
        return False

    five_sum = 0
    three_sum = 0
    other = []
    for num in nums:
        if num % 5 == 0:
            five_sum += num
        elif num % 3 == 0:
            three_sum += num
        else:
            other.append(num)

    def recursive_helper(index, five_sum, three_sum):
        if index == len(other):
            if five_sum == three_sum:
                return True
            else:
                return False

        if recursive_helper(index + 1, five_sum + other[index], three_sum):
            return True

        if recursive_helper(index + 1, five_sum, three_sum + other[index]):
            return True

        return False

    return recursive_helper(0, five_sum, three_sum)
